### ISSUE TITLE
large samples

### ISSUE THREAD

**Issue by sk0427** [chrchang/eigensoft#4]
Hi 

I am trying to PCA with smartpca for 200K sample , 100K SNPS with  256G memory .
However, the process does not finish (core dumped).  I suspect memory shortage, but I do not have access to additional memories. 

Is this problem is reasonable(compared with memory size)? and Are there any way to solve it?

Thanks,

Satoshi

**Comment by chrchang** [comment]
You should use the 'fastmode' from EIGENSOFT 6 or later (or equivalently, plink 2.0's "--pca approx" function); that approximation algorithm is simultaneously faster and more memory-efficient in this case.

**Comment by sk0427** [comment]
Thanks! But I already tried fastmode. I got the result using small samples (like with "poplistname" option), however, using all samples it does not work. 

Is it impossible to?

**Comment by chrchang** [comment]
You have enough memory for the job; maybe you've hit an EIGENSOFT fastmode bug.  Try plink 2.0 "--pca approx" then.

**Comment by sk0427** [comment]
Thank you great advice!
I'll try plink2!
